//! Desktop (GTK) theme contracts.
//!
//! Everything here is headless: the CSS parser and the palette mapping are pure,
//! and the app-side override layer is exercised through `theme::install_gtk` /
//! `theme::clear_gtk` rather than through a real GTK probe (which needs a
//! display and the main thread). The pixels themselves — whether the app really
//! repaints within a second of a `gtk.css` edit — are the manual UAT run.

use gpui::rgb;
use webtmux::theme::{self, GtkPalette};
use webtmux::themes_generated::UI_THEMES;
use webtmux_settings::Theme as SettingsTheme;

/// The desktop palette lives in a process-global `static`; serialize the tests
/// that mutate it so parallel test threads cannot observe each other.
static PALETTE_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn palette() -> GtkPalette {
    GtkPalette {
        is_dark: true,
        bg_primary: rgb(0x1a1b26),
        bg_secondary: rgb(0x16161e),
        bg_tertiary: rgb(0x1f2335),
        bg_card: rgb(0x282a38),
        bg_card_hover: rgb(0x2f334d),
        text_primary: rgb(0xa9b1d6),
        text_secondary: rgb(0x9aa5ce),
        text_tertiary: rgb(0x737aa2),
        text_disabled: rgb(0x484c5f),
        border: rgb(0x373949),
        border_subtle: rgb(0x2a2c3a),
        accent: rgb(0xf7768e),
        accent_hover: rgb(0xff8fa3),
        on_accent: rgb(0x222222),
        error: rgb(0xf7768e),
        warning: rgb(0xe0af68),
        success: rgb(0x9ece6a),
        placeholder: rgb(0x6a6f8a),
        close_hover: rgb(0xd85f74),
        destructive_foreground: rgb(0x222222),
        selection: rgb(0x7aa2f7),
        muted: rgb(0x1f2335),
        input: rgb(0x16161e),
    }
}

/// The old preset literals are the contract the FE parity tests rely on: with no
/// desktop palette installed, every accessor must still return them verbatim.
#[test]
fn preset_literals_are_locked_without_gtk() {
    let _serial = PALETTE_LOCK.lock().unwrap();
    theme::clear_gtk();
    assert!(!theme::gtk_active());

    // Canonical `default-dark` values (FE ui-themes.ts).
    assert_eq!(theme::preset_bg("default-dark"), rgb(0x1e1e1e));
    assert_eq!(theme::preset_fg("default-dark"), rgb(0xd4d4d4));
    assert_eq!(theme::preset_card("default-dark"), rgb(0x1e1e1e));
    assert_eq!(theme::preset_card_fg("default-dark"), rgb(0xd4d4d4));
    assert_eq!(theme::preset_primary("default-dark"), rgb(0xd4d4d4));
    assert_eq!(theme::preset_muted("default-dark"), rgb(0x2d2d2d));
    assert_eq!(theme::preset_muted_fg("default-dark"), rgb(0x808080));
    assert_eq!(theme::preset_border("default-dark"), rgb(0x3c3c3c));
    assert_eq!(theme::preset_accent("default-dark"), rgb(0x2d2d2d));
    assert_eq!(theme::preset_destructive("default-dark"), rgb(0x7f1d1d));
    assert_eq!(theme::preset_input("default-dark"), rgb(0x3c3c3c));
    assert_eq!(theme::preset_ring("default-dark"), rgb(0x808080));

    // Every one of the 102 presets still reads its own generated bytes.
    for p in UI_THEMES {
        assert_eq!(theme::preset_bg(p.name), rgb(p.background), "{} bg", p.name);
        assert_eq!(theme::preset_fg(p.name), rgb(p.foreground), "{} fg", p.name);
        assert_eq!(theme::preset_card(p.name), rgb(p.card), "{} card", p.name);
        assert_eq!(theme::preset_border(p.name), rgb(p.border), "{} border", p.name);
        assert_eq!(
            theme::preset_primary(p.name),
            rgb(p.primary),
            "{} primary",
            p.name
        );
        assert_eq!(
            theme::preset_accent(p.name),
            rgb(p.accent),
            "{} accent",
            p.name
        );
        assert_eq!(
            theme::preset_destructive(p.name),
            rgb(p.destructive),
            "{} destructive",
            p.name
        );
        assert_eq!(
            theme::preset_raw(p.name, theme::PresetToken::Background),
            rgb(p.background),
            "{} raw bg",
            p.name
        );
    }
}

#[test]
fn gtk_palette_drives_every_app_token() {
    let _serial = PALETTE_LOCK.lock().unwrap();
    theme::clear_gtk();
    theme::install_gtk(palette());

    assert!(theme::gtk_active());
    // Polarity follows the palette, not the preset name.
    assert!(theme::preset_is_dark("default-light"));

    assert_eq!(theme::preset_bg("default-dark"), rgb(0x1a1b26));
    assert_eq!(theme::preset_card("default-dark"), rgb(0x282a38));
    assert_eq!(theme::preset_fg("default-dark"), rgb(0xa9b1d6));
    assert_eq!(theme::preset_muted("default-dark"), rgb(0x1f2335));
    assert_eq!(theme::preset_muted_fg("default-dark"), rgb(0x9aa5ce));
    assert_eq!(theme::preset_border("default-dark"), rgb(0x373949));
    assert_eq!(theme::preset_accent("default-dark"), rgb(0xf7768e));
    assert_eq!(theme::preset_primary("default-dark"), rgb(0xf7768e));
    assert_eq!(theme::preset_primary_fg("default-dark"), rgb(0x222222));
    assert_eq!(theme::preset_input("default-dark"), rgb(0x16161e));
    assert_eq!(theme::preset_ring("default-dark"), rgb(0xf7768e));
    assert_eq!(theme::preset_danger_text("default-dark"), rgb(0xf7768e));

    // The status-page / accent helpers follow the same source.
    assert_eq!(theme::bg_color(), rgb(0x1a1b26));
    assert_eq!(theme::fg_color(), rgb(0xa9b1d6));
    assert_eq!(theme::card_bg(), rgb(0x282a38));
    assert_eq!(theme::border_color(), rgb(0x373949));
    assert_eq!(theme::destructive_color(), rgb(0xf7768e));
    assert_eq!(theme::success_accent(), rgb(0x9ece6a));
    assert_eq!(theme::warning_accent(), rgb(0xe0af68));

    // Preset layering stays byte-identical underneath the override.
    assert_eq!(
        theme::preset_raw("default-dark", theme::PresetToken::Background),
        rgb(0x1e1e1e)
    );

    theme::clear_gtk();
    assert_eq!(theme::preset_bg("default-dark"), rgb(0x1e1e1e));
}

#[test]
fn settings_theme_round_trips_gtk() {
    let gtk: SettingsTheme = serde_json::from_str("\"gtk\"").expect("gtk must parse");
    assert_eq!(gtk, SettingsTheme::Gtk);
    assert!(gtk.is_gtk());
    assert_eq!(gtk.as_str(), "gtk");
    assert_eq!(SettingsTheme::parse_lossy("GTK"), SettingsTheme::Gtk);
    assert_eq!(
        serde_json::to_string(&SettingsTheme::Gtk).unwrap(),
        "\"gtk\""
    );
}

#[test]
fn gtk_probe_is_absent_headless() {
    // No `gtk::init()` ran in this process, so the probe must degrade to `None`
    // instead of panicking or blocking.
    assert!(webtmux::gtk_theme::current_key().is_none());
    assert!(webtmux::gtk_theme::palette().is_none());
}
