//! Views module.

pub mod create_session_dialog;
pub mod palette;
pub mod pane_context_menu;
pub mod pane_grid;
pub mod pane_view;
pub mod reconnect_banner;
pub mod rename_pane_dialog;
pub mod rename_session_dialog;
pub mod rename_window_dialog;
pub mod session_context_menu;
pub mod session_states;
pub mod settings;
pub mod sidebar;
pub mod status;
pub mod tab_strip;
pub mod terminal_view;
pub mod toasts;
pub mod window_toolbar;
