// Generate the native GTK theme catalog from the existing web theme sources.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");

function extractArray(path, declaration, endComment) {
  const src = readFileSync(path, "utf8");
  const decl = src.indexOf(declaration);
  if (decl < 0) throw new Error(`missing ${declaration}`);
  const start = src.indexOf("[", decl);
  const marker = src.indexOf(endComment, start);
  const end = src.lastIndexOf("]", marker);
  if (start < 0 || marker < 0 || end < start) throw new Error(`cannot parse ${path}`);
  return vm.runInNewContext(`(${src.slice(start, end + 1)})`);
}

const ui = extractArray(
  join(root, "fe", "src", "features", "settings", "data", "ui-themes.ts"),
  "export const uiThemes",
  "// Look up a UI theme",
);
const terminal = extractArray(
  join(root, "fe", "src", "features", "settings", "data", "terminal-themes.ts"),
  "export const terminalThemes",
  "// Look up a preset",
);

const q = JSON.stringify;
const uiFields = [
  ["background", "Background"], ["foreground", "Foreground"], ["card", "Card"],
  ["cardForeground", "CardForeground"], ["primary", "Primary"],
  ["primaryForeground", "PrimaryForeground"], ["secondary", "Secondary"],
  ["secondaryForeground", "SecondaryForeground"], ["muted", "Muted"],
  ["mutedForeground", "MutedForeground"], ["accent", "Accent"],
  ["accentForeground", "AccentForeground"], ["destructive", "Destructive"],
  ["destructiveForeground", "DestructiveForeground"], ["border", "Border"],
  ["input", "Input"], ["ring", "Ring"],
];
const termFields = [
  ["foreground", "Foreground"], ["background", "Background"], ["cursor", "Cursor"],
  ["black", "Black"], ["red", "Red"], ["green", "Green"], ["yellow", "Yellow"],
  ["blue", "Blue"], ["magenta", "Magenta"], ["cyan", "Cyan"], ["white", "White"],
  ["brightBlack", "BrightBlack"], ["brightRed", "BrightRed"],
  ["brightGreen", "BrightGreen"], ["brightYellow", "BrightYellow"],
  ["brightBlue", "BrightBlue"], ["brightMagenta", "BrightMagenta"],
  ["brightCyan", "BrightCyan"], ["brightWhite", "BrightWhite"],
];

let out = `// Code generated by desktop-gtk/scripts/gen-themes.mjs; DO NOT EDIT.\n\npackage ui\n\n`;
out += `type ThemeColors struct {\n${uiFields.map(([, f]) => `\t${f} string`).join("\n")}\n}\n`;
out += `type ThemePreset struct { Name, Label, TerminalTheme string; Colors ThemeColors }\n`;
out += `type TerminalColors struct {\n${termFields.map(([, f]) => `\t${f} string`).join("\n")}\n}\n`;
out += `type TerminalThemePreset struct { Name, Label string; Colors TerminalColors }\n`;
out += `const DefaultThemeName = ${q(ui[0].name)}\n\nvar Themes = []ThemePreset{\n`;
for (const t of ui) {
  out += `\t{Name:${q(t.name)},Label:${q(t.label)},TerminalTheme:${q(t.terminalTheme)},Colors:ThemeColors{\n`;
  for (const [key, field] of uiFields) out += `\t\t${field}:${q(t.colors[key])},\n`;
  out += `\t}},\n`;
}
out += `}\n\nvar TerminalThemes = []TerminalThemePreset{\n`;
for (const t of terminal) {
  out += `\t{Name:${q(t.name)},Label:${q(t.label)},Colors:TerminalColors{\n`;
  for (const [key, field] of termFields) out += `\t\t${field}:${q(t.colors[key])},\n`;
  out += `\t}},\n`;
}
out += `}\n`;

const target = join(root, "desktop-gtk", "internal", "ui", "themes_gen.go");
writeFileSync(target, out);
console.log(`wrote ${target}: ${ui.length} UI themes, ${terminal.length} terminal themes`);

